---
title: "Estratificación del Dengue usando Estadística Multivariada"
author: "Felipe Antonio Dzul Manzanilla"
institute: "Especialidad en Métodos Estadísticos"
date: "2022/12/06 (updated: `r Sys.Date()`)"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: 
      - default
      - default-fonts
      - duke-blue
      - hygge-duke
      - libs/cc-fonts.css
      - libs/figure-captions.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---


```{r xaringan-fit-screen, echo=FALSE}
xaringanExtra::use_fit_screen()
```

```{r xaringanExtra, echo = FALSE}
xaringanExtra::use_progress_bar(color = "#0051BA", location = "top")
```

```{r xaringan-tachyons, echo=FALSE}
xaringanExtra::use_tachyons()
```

```{r share-again, echo=FALSE}
xaringanExtra::use_share_again()
```


## Modelo de Estratificación del Dengue en México

```{r, echo=FALSE}
DiagrammeR::grViz("digraph {
                  # graph definitions
  graph [layout = dot, rankdir = TB]
  
  # node definitions
  node [shape = rectangle, style = filled, color = grey] 
   
  # dengue
  dataset [label = 'Base de Datos',  fillcolor =  'Orange', color = 'white', fontcolor = 'black']
  
  sinave [label = 'Sinave',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white']
  cases [label = 'Casos',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white']
  cases_a [label = '2008-2015',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white']
  cases_b [label = '2016-2021',  fillcolor =  'DodgerBlue', color = 'white', fontcolor = 'white']
  
  sinave -> cases -> {cases_a[arrowhead = 'crow', arrowtail = 'box', color = 'white'] cases_b} -> dataset
  
  # worldclim
  worldclim [label = 'WorldClim',  fillcolor =  'SeaGreen', color = 'white', fontcolor = 'white']
  bios [label = 'Bio1-Bio19',  fillcolor =  'SeaGreen', color = 'white', fontcolor = 'white']
  worldclim -> bios -> dataset
  
}",
                  height = 300)
```





